name = "publicidad"
main = "worker.js"
compatibility_date = "2024-06-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
API_ORIGIN = "https://www.vecino.com.ve/publicidad/api/index.php"
